### ISSUE TITLE
Use Instagram-PHP-API fork to work with new Instagram API 

### ISSUE THREAD

**Issue by jamestowers** [mayoz/instagram#1]
It doesn't look like @cosenary is going to update the Instagram-PHP-API to work with the new Instagram API changes but @florianbeer has forked his repo to make it work, any chance you could use his fork instead so that we can get this package to work?

**Comment by mayoz** [comment]
I'll update the gateway package as soon. Now, busy a bit.

**Comment by florianbeer** [comment]
hi, you're very welcome to use my fork. I try to integrate pull requests into it and it should stay in a working condition since I use it in a production app.
